import { ThresholdDef, TimeMode } from '../types';
import { useContainerSize } from './useContainerSize';

export function TimelineDiagnosticsPanel({ timeline, selectedHour, elev, solarAz, crossAz, frontAz, anchor, mode, eventTime, status, diagnostics, onEnlarge, isMain }: { timeline: Array<{ h: number; e: number }>; selectedHour: number; elev: number; solarAz: number; crossAz: number; frontAz: number; anchor: ThresholdDef; mode: TimeMode; eventTime: string; status: string; diagnostics: Array<{ threshold: string; eventTime: string; xGroundKm: number | null; groundAngleDeg: number | null; angleAt90Deg: number | null; angleAt110Deg: number | null; status: string }>; onEnlarge?: () => void; isMain?: boolean }) {
  const { ref, size } = useContainerSize<HTMLDivElement>();
  const compact = !isMain;
  const w = Math.max(320, size.width || 720), h = Math.max(compact ? 150 : 250, (size.height || 340) - (compact ? 120 : 210));
  const p = compact ? 28 : 42;
  const min = -30, max = 60;
  const sx = (x: number) => p + (x / 24) * (w - 2 * p), sy = (y: number) => h - p - ((y - min) / (max - min)) * (h - 2 * p);
  const thresholds = [{ y: 0, c: '#1d4ed8', label: 'Horizon 0°' }, { y: -6, c: '#059669', label: 'Civil -6°' }, { y: -12, c: '#d97706', label: 'Nautical -12°' }, { y: -18, c: '#7c3aed', label: 'Astronomical -18°' }];
  const fmt = (v: number | null, d = 1) => (v == null || !Number.isFinite(v) ? 'N/A' : v.toFixed(d));
  return <div className='panel'><div className='panelHeader'><h4>Solar Timeline & Diagnostics</h4>{!isMain && onEnlarge && <button onClick={onEnlarge}>Enlarge</button>}</div><div className={`panelBody ${compact ? 'timelineSplit compactMode' : 'timelineStack'}`} ref={ref}><svg preserveAspectRatio='none' viewBox={`0 0 ${w} ${h}`}>{thresholds.map(t => <g key={t.y}><line x1={p} x2={w - p} y1={sy(t.y)} y2={sy(t.y)} stroke={t.c} strokeDasharray='4 4' /><text x={w - p + 4} y={sy(t.y) + 4} fontSize={compact ? '8' : '10'}>{t.label}</text></g>)}<polyline fill='none' stroke='#2563eb' strokeWidth='2' points={timeline.map(d => `${sx(d.h)},${sy(d.e)}`).join(' ')} /><line x1={sx(selectedHour)} x2={sx(selectedHour)} y1={p} y2={h - p} stroke='#ef4444' /><text x={w / 2} y={h - 6} fontSize={compact ? '9' : '11'} textAnchor='middle'>{compact ? 'UTC [h]' : 'UTC time [h]'}</text><text x={12} y={h / 2} fontSize={compact ? '9' : '11'} transform={`rotate(-90 12 ${h / 2})`} textAnchor='middle'>{compact ? 'Solar elev. [deg]' : 'Solar elevation [deg]'}</text></svg>
    <table className={compact ? 'compactTable' : ''}><tbody><tr><td>Solar elevation now</td><td>{elev.toFixed(2)}°</td></tr><tr><td>Solar azimuth now</td><td>{solarAz.toFixed(2)}°</td></tr><tr><td>Cross-section azimuth</td><td>{crossAz.toFixed(2)}°</td></tr><tr><td>Terminator-front azimuth</td><td>{frontAz.toFixed(2)}°</td></tr><tr><td>Anchor</td><td>{anchor.label}</td></tr><tr><td>event time</td><td>{eventTime || 'N/A'}</td></tr><tr><td>Status</td><td>{status || 'N/A'}</td></tr></tbody></table>
    <table className={compact ? 'compactTable' : ''}><thead><tr><th>Threshold</th><th>Time</th><th>Xg [km]</th><th>∠ground [°]</th><th>∠@90 km [°]</th><th>∠@110 km [°]</th><th>Status</th></tr></thead><tbody>{diagnostics.map(row => <tr key={row.threshold}><td>{row.threshold}</td><td>{row.eventTime || 'N/A'}</td><td>{fmt(row.xGroundKm, 0)}</td><td>{fmt(row.groundAngleDeg, 2)}</td><td>{fmt(row.angleAt90Deg, 2)}</td><td>{fmt(row.angleAt110Deg, 2)}</td><td>{row.status || 'N/A'}</td></tr>)}</tbody></table></div></div>;
}
